// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// UserColumns holds the columns for the "User" table.
	UserColumns = []*schema.Column{
		{Name: "Id", Type: field.TypeUUID},
		{Name: "UserName", Type: field.TypeString},
		{Name: "Email", Type: field.TypeString, Unique: true},
		{Name: "NormalizedEmail", Type: field.TypeString},
		{Name: "PasswordHash", Type: field.TypeString},
		{Name: "EmailConfirmed", Type: field.TypeBool, Default: false},
		{Name: "PhoneNumberConfirmed", Type: field.TypeBool, Default: false},
		{Name: "TwoFactorEnabled", Type: field.TypeBool, Default: false},
		{Name: "LockoutEnabled", Type: field.TypeBool, Default: false},
		{Name: "AccessFailedCount", Type: field.TypeInt, Default: 0},
	}
	// UserTable holds the schema information for the "User" table.
	UserTable = &schema.Table{
		Name:       "User",
		Columns:    UserColumns,
		PrimaryKey: []*schema.Column{UserColumns[0]},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		UserTable,
	}
)

func init() {
}
