// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fiber-be-template/ent/schema"
	"fiber-be-template/ent/user"

	"github.com/google/uuid"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	userFields := schema.User{}.Fields()
	_ = userFields
	// userDescUsername is the schema descriptor for username field.
	userDescUsername := userFields[1].Descriptor()
	// user.UsernameValidator is a validator for the "username" field. It is called by the builders before save.
	user.UsernameValidator = userDescUsername.Validators[0].(func(string) error)
	// userDescEmail is the schema descriptor for email field.
	userDescEmail := userFields[2].Descriptor()
	// user.EmailValidator is a validator for the "email" field. It is called by the builders before save.
	user.EmailValidator = userDescEmail.Validators[0].(func(string) error)
	// userDescNormalizedEmail is the schema descriptor for normalized_email field.
	userDescNormalizedEmail := userFields[3].Descriptor()
	// user.NormalizedEmailValidator is a validator for the "normalized_email" field. It is called by the builders before save.
	user.NormalizedEmailValidator = userDescNormalizedEmail.Validators[0].(func(string) error)
	// userDescPasswordHash is the schema descriptor for password_hash field.
	userDescPasswordHash := userFields[4].Descriptor()
	// user.PasswordHashValidator is a validator for the "password_hash" field. It is called by the builders before save.
	user.PasswordHashValidator = userDescPasswordHash.Validators[0].(func(string) error)
	// userDescEmailConfirmed is the schema descriptor for email_confirmed field.
	userDescEmailConfirmed := userFields[5].Descriptor()
	// user.DefaultEmailConfirmed holds the default value on creation for the email_confirmed field.
	user.DefaultEmailConfirmed = userDescEmailConfirmed.Default.(bool)
	// userDescPhoneNumberConfirmed is the schema descriptor for phone_number_confirmed field.
	userDescPhoneNumberConfirmed := userFields[6].Descriptor()
	// user.DefaultPhoneNumberConfirmed holds the default value on creation for the phone_number_confirmed field.
	user.DefaultPhoneNumberConfirmed = userDescPhoneNumberConfirmed.Default.(bool)
	// userDescTwoFactorEnabled is the schema descriptor for two_factor_enabled field.
	userDescTwoFactorEnabled := userFields[7].Descriptor()
	// user.DefaultTwoFactorEnabled holds the default value on creation for the two_factor_enabled field.
	user.DefaultTwoFactorEnabled = userDescTwoFactorEnabled.Default.(bool)
	// userDescLockoutEnabled is the schema descriptor for lockout_enabled field.
	userDescLockoutEnabled := userFields[8].Descriptor()
	// user.DefaultLockoutEnabled holds the default value on creation for the lockout_enabled field.
	user.DefaultLockoutEnabled = userDescLockoutEnabled.Default.(bool)
	// userDescAccessFailedCount is the schema descriptor for access_failed_count field.
	userDescAccessFailedCount := userFields[9].Descriptor()
	// user.DefaultAccessFailedCount holds the default value on creation for the access_failed_count field.
	user.DefaultAccessFailedCount = userDescAccessFailedCount.Default.(int)
	// userDescID is the schema descriptor for id field.
	userDescID := userFields[0].Descriptor()
	// user.DefaultID holds the default value on creation for the id field.
	user.DefaultID = userDescID.Default.(func() uuid.UUID)
}
